server:
  port: 8080
---

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://rak2279.ctlcuxtqxdwe.eu-central-1.rds.amazonaws.com:5432/postgres
    username: postgres
    password: wndfkr12345

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        ddl-auto: update
        temp:
          use_jdbc_metadata_defaults: false
          
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: delivery
          destination: flowerdeliverywm
          contentType: application/json
        event-out:
          destination: flowerdeliverywm
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug
server:
  port: 8084
---

spring:
  profiles: docker
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: delivery
          destination: flowerdeliverywm
          contentType: application/json
        event-out:
          destination: flowerdeliverywm
          contentType: application/json
